[package]
name = "nais_client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio02 = { package = "tokio", version = "0.2", features = ["rt-threaded", "macros", "time"] }
irc = "0.14"
clap = { version = "4", features = ["derive"] }
log = "0.4"
env_logger = "0.10"
dioxus = { version = "0.5", features = ["desktop"] }
async-channel = "2"
futures = "0.3"
futures-timer = "3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs = "5"
